version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vxpgif7n4flm"
s3_prefix = "hello-world"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
